server:
  port: 8085
spring:
  datasource:
    url: jdbc:h2:mem:dbAssignment
    driverClassName: org.h2.Driver
    username: siwar
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
