server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://siwar:JyhsWiLByN52YyQ2iZTh@gitlab.tech.orange/pfe-team-2023/socleit.git
          search-paths: socleit-config
          